# 1-Dimensional Array

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


# 2-Dimensional Array

In [2]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Initialize all the elements of x X y array to 0

In [3]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrange the numbers between x and y with an interval of z

In [4]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
#even numbers between 10 and 20
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

# Arrange 'z' numbers between x and y

In [6]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [7]:
#even numbers between 0 to 10
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling SAME number in an array of dimension x X y

In [8]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

# Filling RANDOM number in an array of dimension x X y

In [9]:
np.random.random((2,3))

array([[0.64342117, 0.15332063, 0.55228129],
       [0.26454612, 0.35402784, 0.67748623]])

# Inspecting the array: Checking the size of the array

In [10]:
a = np.array([[2,3,4],[4,4,6]])
print(a.shape)

(2, 3)


In [11]:
s = np.array([[1,2,3,4],[2,3,4,6],[6,7,8,9]])
print(s.shape)

(3, 4)


# Inspecting the array: Resize the Array

In [12]:
a = np.array([[2,3,4],[4,4,6]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 4]
 [4 6]]


In [13]:
a = np.array([[2,3,4,4],[2,4,4,6]])
a.shape = (8,1) #Trick: x*y = Total number of elements in the array
print(a)

[[2]
 [3]
 [4]
 [4]
 [2]
 [4]
 [4]
 [6]]


# Return the dimension of the array

In [14]:
a = np.arange(25)
a
#print(a.ndim)
#reshape our array
#b = a.reshape(12,2) #trick: Calculate the factors of 24: 1,2,3,4,6,12,24 
#print(b.ndim)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# Find the number of elements in an array

In [15]:
print(a.size)

25


In [16]:
d = np.array([[1,2,3,4],[4,5,6,4],[6,7,8,9]])
print(d.size)

12


# Find the datatype of the array

In [17]:
a = np.arange(24, dtype=float)
print(a.dtype)
a

float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

# Numpy Array Mathematics: Addition

In [18]:
import numpy as np
np.sum([10,20])

30

In [19]:
#using a variable that is sum of a+b
a,b = 10,20
np.sum([a,b])

30

In [20]:
np.sum([[1,2],[5,6]],axis = 0)

array([6, 8])

In [21]:
np.sum([[1,2],[5,6]],axis = 1)

array([ 3, 11])

In [22]:
np.sum([[1,2],[5,6]])

14

# Numpy Array Mathematics: Subtraction

In [23]:
np.subtract(10,20)

-10

# All other numpy Mathematics Function

In [24]:
np.multiply(2,3) #Multiplying two numbers

6

In [25]:
np.divide(10,5) #Dividing two numbers

2.0

In [26]:
a =np.array([2,4,6])
b =np.array([1,2,3])
np.multiply(a,b)

array([ 2,  8, 18])

In [27]:
#exp,sqrt,sin,cos,log
print("Exponent : ",np.exp(a))
print("Square root : ", np.sqrt(a))
print("Sin : ", np.sin(a))
print("Cos : ", np.cos(a))
print("Log : ", np.log(a))

Exponent :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos :  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


# Array Comparison

In [28]:
#Element-wise Comparison
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.equal(a,b)

array([False, False,  True])

In [29]:
#Array-wise Comparison
a = [1,2,4]
b = [1,4,4]
c = [1,2,4]
np.array_equal(a,c)

True

# Aggregate Function

In [30]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
print("Sum: ",np.sum(a))
print("Minimum Value: ",np.min(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Coorelation Coefficient: ",np.corrcoef(a))
print("Standard Deviation: ",np.std(a))


Sum:  7
Minimum Value:  1
Mean:  2.3333333333333335
Median:  2.0
Coorelation Coefficient:  1.0
Standard Deviation:  1.247219128924647


# Concept of Broadcasting

In [75]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')

First Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



# Indexing and Slicing in Python

In [77]:
a = ['m','o','n','t','y',' ','p','y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

In [81]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]
a[:1]
print(a)
a[:1,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3]])

In [82]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [83]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

# Array Manipulation in Python

In [84]:
a = np.array([1,2,3])
b= np.array([4,5,6])
#concatenation of two arrays
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [86]:
#Stack array row-wise: Horizontal 
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [85]:
#Stack array row-wise: Vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
#Combining Column-wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [98]:
# Splitting Array

In [99]:
x = np.arange(16).reshape(4,4)
print(x,"\n\n")
print(np.hsplit(x,2))
print("\n\n", np.hsplit(x,np.array([2,3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


# Advantages of Numpy Over a List


In [101]:
#Numpy vs List: Memory size
import numpy as np
import sys

#define a list
l = range(1000)
print("Size of a list: ",sys.getsizeof(1)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of an array: ",a.size*a.itemsize)

Size of a list:  28000
Size of an array:  4000


In [140]:
#Numpy vs List: Speed
import time
def using_List():
    t1 = time.time()#Starting/Initial Time
    X = range(10000)
    Y = range(10000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(10000)
    b = np.arange(10000)
    z =a+b #more convient than a list
    return time.time()-t1
list_time = using_List()
numpy_time = using_Numpy()
print(list_time,numpy_time)
print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

0.001993894577026367 0.000997781753540039
In this example Numpy is 1.9983273596176823 times faster than a list
