In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
li1 = [1,2,3,4,5,6,7,8]
np.array(li1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.array([1,2,3,False,True],dtype=bool)

array([ True,  True,  True, False,  True])

In [ ]:
bool(1)

True

In [ ]:
bool(-900)

True

In [ ]:
bool(99)

True

In [ ]:
bool('False')

True

In [ ]:
bool(None)

False

In [ ]:
bool(False)

False

In [ ]:
bool(' ')

True

In [ ]:
bool('')

False

In [ ]:
bool([])

False

In [ ]:
np.array([0,1,4,5],dtype=str)

array(['0', '1', '4', '5'], dtype='<U1')

In [ ]:
narr1 = np.arange(1,11)
narr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
type(narr1)

numpy.ndarray

In [ ]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3),dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [ ]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.full((3,3),'x')

array([['x', 'x', 'x'],
       ['x', 'x', 'x'],
       ['x', 'x', 'x']], dtype='<U1')

In [ ]:
np.full((3,5),[1,2,3,4,5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
np.full((3,2,2),[[1,2],[3,4]])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [ ]:
np.random.random((2,2))

array([[0.75459397, 0.91703834],
       [0.38601312, 0.65714665]])

In [ ]:
np.random.randint(1,10,9).reshape((3,3))

array([[5, 7, 2],
       [4, 4, 9],
       [7, 4, 8]])

In [ ]:
np.empty((2,2),dtype=int)

array([[4604971997799931966, 4606435166572816331],
       [4600625414114086730, 4604094270406392150]])

In [ ]:
np.linspace(1,10,5,dtype=str)

array(['1.0', '3.25', '5.5', '7.75', '10.0'], dtype='<U32')

In [ ]:
narr2 = np.arange(10,1001,10)
narr2

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000])

In [ ]:
narr2[4]

50

In [ ]:
narr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
narr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
narr3[0,0]

1

In [ ]:
narr3[0][0]

1

In [ ]:
narr3[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
narr3[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [ ]:
narr4 = np.array([1,2,3,4,5])
narr4

array([1, 2, 3, 4, 5])

In [ ]:
np.insert(narr4,1,10)

array([ 1, 10,  2,  3,  4,  5])

In [ ]:
np.insert(narr4,3,[100,200,300])

array([  1,   2,   3, 100, 200, 300,   4,   5])

In [ ]:
n = int(input("Number of values to insert: "))

for i in range(n):
  narr4 = np.insert(narr4,int(input("Index Value: ")),int(input("Value: ")))

narr4

Number of values to insert: 1
Index Value: 1
Value: 1111


array([   1, 1111,  111,    2,  200,    3,    4,  500,    5])

In [ ]:
narr4 = np.array([1,2,3,4,5])
narr4

array([1, 2, 3, 4, 5])

In [ ]:
narr4 = np.insert(narr4,2,200)
narr4 = np.insert(narr4,5,500)

In [ ]:
narr4

array([  1,   2, 200,   3,   4, 500,   5])

In [ ]:
narr4

array([  1,   2, 200,   3,   4, 500,   5])

In [ ]:
narr4 = np.delete(narr4,0)
narr4

array([  2, 200,   3,   4, 500,   5])

In [ ]:
narr4 = np.delete(narr4,[1,2])
narr4

array([  2,   5, 200, 500])

In [ ]:
narr4.sort()

In [ ]:
narr4

array([  2,   3,   4,   5, 200, 500])