# Numpy Advance Assignment

## Module-4-Numpy-Advance-3

### Module 4: Numpy Assignment

#### Problem Statement:

You work in XYZ Company as a Python. The company officials want you to build a python program.

#### Tasks to be performed:
1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]


2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.


3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]


4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]


5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0)

In [4]:
# Taking tuple in function argument and generate an array

import numpy as np

def solve(dim_tuple,fillnumber):

    return np.full(dim_tuple,fillnumber)

x= solve((3,3),5)

print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
# NumPy 1D Array Sums

from numpy import *

arr1 = array([5,10,15,20,30])
arr2 = array([55,16,1,280,60])

def add(*arr):
    arr3 = ([])
    k =0
    for num1 in arr1:
        num3 = num1 + arr2[k]
        arr3.append(num3)
        k +=1
    print("Result after adding:\n")    
    print(arr3)
    
add(arr1, arr2)

Result after adding:

[60, 26, 16, 300, 90]


In [8]:
# Numpy 2D array User input & Top left corner slicing matrix

from numpy import *
import numpy as np

def sliceMatrix():
    
    m = int(input("Enter no of Rows: "))
    n = int(input("Enter no of Columns: "))
    # Initialize Matrix by zeros
    a = zeros((m,n), dtype=int)
    u=len(a)
    
    # Taking input from User 
    for i in range(u):
            for j in range(len(a[i])):
                x= int(input("Enter element: "))
                a[i][j] = x
                
    print("Input Matrix:\n",a)
    print("\n Shape of Input Matrix: ",a.shape)
    
    b = a[:m-1,:n-1]
    print("\nSlicing Matrix:\n", b)
    print("\nShape of Slicing Matrix: ",b.shape)
    
sliceMatrix()

Enter no of Rows: 3
Enter no of Columns: 3
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
Enter element: 5
Enter element: 6
Enter element: 7
Enter element: 8
Enter element: 9
Input Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Shape of Input Matrix:  (3, 3)

Slicing Matrix:
 [[1 2]
 [4 5]]

Shape of Slicing Matrix:  (2, 2)


In [9]:
# Numpy 2D array User input & Bottom Right corner slicing matrix

from numpy import *
import numpy as np

def BsliceMatrix():
    
    m = int(input("Enter no of Rows: "))
    n = int(input("Enter no of Columns: "))
    # Initialize Matrix by zeros
    a = zeros((m,n), dtype=int)
    u=len(a)
    
    # Taking input from User 
    for i in range(u):
            for j in range(len(a[i])):
                x= int(input("Enter element: "))
                a[i][j] = x
                
    print("Input Matrix:\n",a)
    print("\n Shape of Input Matrix: ",a.shape)
    
    b = a[m-2:,n-2:]
    print("\nSlicing Matrix:\n", b)
    print("\nShape of Slicing Matrix: ",b.shape)
    
BsliceMatrix()

Enter no of Rows: 3
Enter no of Columns: 3
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
Enter element: 5
Enter element: 6
Enter element: 7
Enter element: 8
Enter element: 9
Input Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Shape of Input Matrix:  (3, 3)

Slicing Matrix:
 [[5 6]
 [8 9]]

Shape of Slicing Matrix:  (2, 2)


In [20]:
# Using User defined 1D array to calculate Mean & Standard Deviation

from numpy import *
import numpy as np

def getArray():
    lst = []
    
    # number of elements as input
    n = int(input("Enter number of elements : "))
    
    # iterating till the range
    for i in range(0, n):
        ele = int(input("Enter Elemnt: "))
        lst.append(ele)
    
    # Converting List to Array
    a = np.array(lst)
    print("Your entered 1D Array: ", a)
    
    # Calculating Mean & Std_Dev
    r1 = np.mean(a)
    print("\nMean: ", r1)
    
    r2 = np.std(a)
    print("Std_Dev: ", r2)
    
getArray()


Enter number of elements : 3
Enter Elemnt: 1
Enter Elemnt: 1
Enter Elemnt: 1
Your entered 1D Array:  [1 1 1]

Mean:  1.0
Std_Div:  0.0
