In [59]:
#Empty tuple will provide you type as tuple only
#But if there is single element you are putting at the time of assigning the tuple.
#Then it is must to provide comma after that, because without comma if single element will be there,
#It will consider the data type of that element and not create a tuple.

t = (1,)

In [60]:
type(t)

tuple

In [61]:
print(t)

(1,)


In [ ]:
pip install numpy

In [137]:
# Create a numpy array with numpy.array module and with a data type integer and float.

import numpy as np

arr = np.array([1,2,3,4,5.5,6.5])

In [138]:
print(arr)

[1.  2.  3.  4.  5.5 6.5]


In [139]:
print(arr.dtype)

float64


In [17]:
arr1 = np.array([1,2,3,4,5,6.2])

In [18]:
print(arr1)

[1.  2.  3.  4.  5.  6.2]


In [21]:
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

a = arr3.astype('f')

[1 2 3 4 5 6]


In [20]:
print(a)

[1. 2. 3. 4. 5. 6.]


In [186]:
arr4 = np.array([2,4.2,5,6.6,7.3,8], dtype='i')
print(arr4)

[2 4 5 6 7 8]


In [38]:
# Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
# Also, print the shape and dimensions of the numpy arrays created above.

'''
0d, 1d, 2d, 3d, 4d

() - Zero Dimension

(2) - One Dimension

(2, 3)  - Two Dimension

(2, 3, 4)  - Three Dimension

(2, 3, 4, 5) - Four Dimension
'''

#Zero Dimension
ar1 = np.array(122)
print(ar1)

122


In [39]:
print("Shape :",ar1.shape)

Shape : ()


In [40]:
print("Dimension :",ar1.ndim)

Dimension : 0


In [44]:
#One Dimension
ar1 = np.array([2,4,8,10,45])
print(ar1)

[ 2  4  8 10 45]


In [45]:
print("Shape :",ar1.shape)

Shape : (5,)


In [46]:
print("Dimension :",ar1.ndim)

Dimension : 1


In [47]:
#Two Dimension
ar1 = np.array([[2,4,8],[3,6,9]])
print(ar1)

[[2 4 8]
 [3 6 9]]


In [48]:
print("Shape :",ar1.shape)

Shape : (2, 3)


In [49]:
print("Dimension :",ar1.ndim)

Dimension : 2


In [67]:
#Three Dimension
ar1 = np.array([[[2,4,8],[3,6,9],[4,8,12]]])
print(ar1)

[[[ 2  4  8]
  [ 3  6  9]
  [ 4  8 12]]]


In [68]:
print("Shape :",ar1.shape)

Shape : (1, 3, 3)


In [69]:
print("Dimension :",ar1.ndim)

Dimension : 3


In [102]:
#Three Dimension
ar1 = np.array([1233],ndmin = 3)
print(ar1)

[[[1233]]]


In [103]:
print(ar1.shape)

(1, 1, 1)


In [104]:
print("Dimension :",ar1.ndim)

Dimension : 3


In [98]:
#Four Dimension
ar1 = np.array([[[[1233]]]])
print(ar1)

[[[[1233]]]]


In [99]:
print("Dimension :",ar1.ndim)

Dimension : 4


In [100]:
print("Shape :",ar1.shape)

Shape : (1, 1, 1, 1)


In [108]:
# Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

arr1 = np.identity(2, dtype="i")

In [109]:
print(arr1)

[[1 0]
 [0 1]]


In [110]:
print(arr1.dtype)

int32


In [111]:
arr1 = np.identity(3, dtype="i")

In [112]:
print(arr1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [113]:
arr1 = np.identity(4, dtype="i")

In [115]:
print(arr1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [124]:
# Create a numpy array with shape 2x5 that has all the elements as zero.

a = np.zeros((2,5), dtype='i')

In [125]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [126]:
a = np.array([[0, 0, 0, 0, 0], [0,0 ,0, 0,0]])

In [127]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [167]:
# Create a numpy array that has the shape 3x5 and all the elements are 5.

arr1 = np.full((3,5), 5)

In [168]:
print(arr1)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [169]:
print(arr1.dtype)

int32


In [207]:
#To convert dtype in String

arr1 = np.full((3,5), "ABCD", dtype="S")

In [208]:
print(arr1)

[[b'A' b'A' b'A' b'A' b'A']
 [b'A' b'A' b'A' b'A' b'A']
 [b'A' b'A' b'A' b'A' b'A']]


In [172]:
print(arr1.dtype)

|S1


In [209]:
#To convert dtype in unicode string

arr1 = np.full((3,5), "ABC", dtype="U")

print(arr1)

print(arr1.dtype)

[['A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A']]
<U1


In [210]:
#To convert dtype in float

arr1 = np.full((3,5), 5, dtype="f")

print(arr1)

print(arr1.dtype)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
float32


In [197]:
#To convert dtype in boolean we use 'b'

arr1 = np.full((3,5), 5, dtype="b")

print(arr1)

print(arr1.dtype)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
int8


In [203]:
#To convert dtype in complex we use 'c'

arr1 = np.full((3,5), 'a', dtype="c")

print(arr1)

print(arr1.dtype)

[[b'a' b'a' b'a' b'a' b'a']
 [b'a' b'a' b'a' b'a' b'a']
 [b'a' b'a' b'a' b'a' b'a']]
|S1


In [212]:
#Create a numpy array with random integers in the range 0-100, and the sample size should be 25.

#b=np.arange(0,100,4)

In [234]:
#print(b)

In [239]:
arr = np.random.randint(0,100,25)

In [240]:
print(arr)

[62 45 58 71 24 79  3 48 46  4 96 89 85 36 34 43 79 99 58 42 91 72  4 83
 38]


In [243]:
# Create a numpy array with a shape 3x3 that has all elements as 1.

arr = np.ones((3,3), dtype="i")

In [244]:
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [245]:
arr1 = np.full((3,3), 1)

In [246]:
print(arr1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [248]:
# Create a numpy array in the shape 2x3 with random integers in the range 0-100.
# Reshape the array in the shape 3x2 and print the updated shape of the resultant array

arr1 = np.random.randint(0,100,(2,3))

In [249]:
print(arr1)

[[52 47 21]
 [26 80 65]]


In [251]:
a = arr1.reshape(3,2)

In [252]:
#Updated Shape of the resultant array

print(a)

[[52 47]
 [21 26]
 [80 65]]


In [253]:
print(a.shape)

(3, 2)


In [267]:
'''
Create a numpy array, with the range 0-1000, with a step 2. Perform the
following operations on the same.

a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
#f. Print the last ten elements of the array, using negative indexing
'''

arr1 = np.arange(0, 1000, 2) #Here start = 0, stop = 1000, step = 2

In [268]:
print(arr1)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [270]:
print(arr1[0:10])

[ 0  2  4  6  8 10 12 14 16 18]


In [283]:
print(arr1[-10:])
print(arr1[-1:-11:-1]) #Last 10 digits

[980 982 984 986 988 990 992 994 996 998]
[998 996 994 992 990 988 986 984 982 980]


In [278]:
print(arr1[10:26]) #stop is 26, it will go till 25th index

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [279]:
print(arr1[22])

44


In [288]:
print(arr1[-1::-1]) #Here first -1 is start and last -1 is your step

[998 996 994 992 990 988 986 984 982 980 978 976 974 972 970 968 966 964
 962 960 958 956 954 952 950 948 946 944 942 940 938 936 934 932 930 928
 926 924 922 920 918 916 914 912 910 908 906 904 902 900 898 896 894 892
 890 888 886 884 882 880 878 876 874 872 870 868 866 864 862 860 858 856
 854 852 850 848 846 844 842 840 838 836 834 832 830 828 826 824 822 820
 818 816 814 812 810 808 806 804 802 800 798 796 794 792 790 788 786 784
 782 780 778 776 774 772 770 768 766 764 762 760 758 756 754 752 750 748
 746 744 742 740 738 736 734 732 730 728 726 724 722 720 718 716 714 712
 710 708 706 704 702 700 698 696 694 692 690 688 686 684 682 680 678 676
 674 672 670 668 666 664 662 660 658 656 654 652 650 648 646 644 642 640
 638 636 634 632 630 628 626 624 622 620 618 616 614 612 610 608 606 604
 602 600 598 596 594 592 590 588 586 584 582 580 578 576 574 572 570 568
 566 564 562 560 558 556 554 552 550 548 546 544 542 540 538 536 534 532
 530 528 526 524 522 520 518 516 514 512 510 508 50

In [290]:
print(arr1[:])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [291]:
'''
Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.
'''

arr = np.array([1,2,3,4,5])

In [292]:
print(arr)

[1 2 3 4 5]


In [293]:
# Insert the element 6 at the end of the array.
arr1 = np.append(arr,6)

In [294]:
print(arr1)

[1 2 3 4 5 6]


In [295]:
# Insert the element 10 at the beginning of the array.
arr1 = np.insert(arr1,0,10)

In [296]:
print(arr1)

[10  1  2  3  4  5  6]


In [297]:
# Insert the element 30, before 4.

arr1 = np.insert(arr1, 4, 30)

In [298]:
print(arr1)

[10  1  2  3 30  4  5  6]


In [303]:
# Update the element 5 as 50.

arr1[6] = 50

In [304]:
print(arr1)

[10  1  2  3 30  4 50  6]


In [306]:
# Delete the element 50 in the updated array.

arr1 = np.delete(arr1,6)

In [307]:
print(arr1)

[10  1  2  3 30  4  6]


In [312]:
# Create a function to search for the element 30.

for i in arr1:
    if i == 30:
        print("Searched",i)

Searched 30


In [313]:
#Sort the array in ascending order.

print(np.sort(arr1))

[ 1  2  3  4  6 10 30]


In [316]:
#For Descending Order
arr2 = np.sort(arr1) [::-1]

In [317]:
print(arr2)

[30 10  6  4  3  2  1]
