In [1]:
import numpy as np

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [4]:
arr = np.array([[1, 2, 3, 4, 5, 6]])
arr.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr = np.array([1, 3, 4, 6, 5, 2])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
arr[2:]

array([3, 4, 5, 6])