In [1]:
!conda install numpy --y

Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.11.0               |   py38hecd8cb5_0        14.4 MB
    ------------------------------------------------------------
                                           Total:        14.4 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              conda-forge::conda-4.11.0-py38h50d173~ --> pkgs/main::conda-4.11.0-py38hecd8cb5_0



conda-4.11.0         | 14.4 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


In [2]:
!pip install numpy

You should consider upgrading via the '/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


# Import NumPy

In [3]:
import numpy as np

# Creating Arrays


In [4]:
numpy_array = np.array([1,2,3])

In [5]:
numpy_array

array([1, 2, 3])

In [6]:
type(numpy_array)

numpy.ndarray

In [7]:
type(numpy_array[0])

numpy.int64

In [8]:
## Create 2d Array
b = np.array([[1,2,3], [4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [10]:
numpy_array.shape

(3,)

In [12]:
## Create 3d array
c = np.array([[[1,2,3], [4,5,6], [6,7,8]]])

In [13]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [14]:
c.shape

(1, 3, 3)

## Initializations

In [225]:
zeros = np.zeros((2, 2, 3))

In [226]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
example = np.zeros((2,3))

In [26]:
example

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
zeros.shape

(2, 3)

In [27]:
z = np.zeros(5)

In [28]:
z

array([0., 0., 0., 0., 0.])

In [29]:
z.shape

(5,)

In [30]:
## Initialize with 1s
ones = np.ones((1, 2))

In [31]:
ones

array([[1., 1.]])

## Arranging Number

In [32]:
x = np.arange(5)

In [33]:
x

array([0, 1, 2, 3, 4])

In [34]:
gaps = np.arange(0, 20, 2)

In [35]:
gaps

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
gaps = np.arange(0, 100, 20)

In [37]:
gaps

array([ 0, 20, 40, 60, 80])

In [44]:
## Negative numbers
neg = np.arange(-1, -10, -2)

In [45]:
neg

array([-1, -3, -5, -7, -9])

## Arranging 'z' numbers between two values

In [48]:
d = np.linspace(0, 10, 5)

In [49]:
d

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Creating Array of N Dimenions using Same Numbers

In [50]:
filled_array = np.full((2, 3), 5)

In [51]:
filled_array

array([[5, 5, 5],
       [5, 5, 5]])

## Creating Array of N Dimensions using Random Numbers

In [52]:
random_array = np.random.random((2, 2))

In [53]:
random_array

array([[0.74613376, 0.53143222],
       [0.3874665 , 0.15183376]])

In [54]:
rand_int = np.random.randint(low=0, high=10, size=(15, 2))

In [55]:
rand_int

array([[0, 7],
       [5, 4],
       [5, 7],
       [1, 2],
       [3, 2],
       [1, 7],
       [4, 9],
       [6, 7],
       [3, 6],
       [7, 8],
       [2, 0],
       [0, 7],
       [4, 6],
       [4, 4],
       [8, 2]])

## Reshaping

In [56]:
a = np.arange(24)

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
a.shape

(24,)

In [60]:
b = a.reshape(12, 2)

In [61]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [62]:
b = a.reshape(12, 3)

ValueError: cannot reshape array of size 24 into shape (12,3)

In [74]:
b = a.reshape(6, 2, 2)

In [65]:
b.shape

(6, 2, 2)

In [72]:
b


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

## Finding Size of an Array

In [69]:
x = [[1, 2, 3], [4,5,6]]


In [70]:
len(x)

2

In [68]:
len(b)

6

In [71]:
b.size

24

## Get Dimension

In [75]:
b.shape

(6, 2, 2)

In [76]:
b.ndim

3

## Mathematical Operations

In [77]:
x = np.sum([[1,2], [2,3]])

In [78]:
x

8

In [79]:
y = np.sum([[1,2], [2,3]], axis=0)
y

array([3, 5])

In [80]:
z = np.sum([[1,2], [2,3]], axis=1)
z

array([3, 5])

In [81]:
## Subtraction
a = np.array([3, 2])
b = np.array([1, 2])

In [82]:
np.subtract(a, b)

array([2, 0])

In [83]:
## Multiplication
a = np.array([3, 2])
b = np.array([1, 2])

In [84]:
np.multiply(a, b)

array([3, 4])

In [104]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [105]:
x/4

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [85]:
## Exponential Operations
a = np.array([1, 1])

In [86]:
print(np.exp(a))

[2.71828183 2.71828183]


In [87]:
## Square Root
np.sqrt(a)

array([1., 1.])

In [88]:
## Trignometric Function
print(np.sin(a))

[0.84147098 0.84147098]


In [89]:
print(np.cos(a))

[0.54030231 0.54030231]


In [90]:
print(np.log(a))

[0. 0.]


## Element wise array comparison

In [92]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [96]:
b = np.array([0, 2, 2, 3, 4, 5])
b

array([0, 2, 2, 3, 4, 5])

In [97]:
np.equal(a, b)

array([ True, False,  True,  True,  True,  True])

In [98]:
np.array_equal(a, b)

False

## Aggregate Function

In [99]:
a = np.array([1,2,34,5])

In [100]:
a

array([ 1,  2, 34,  5])

In [101]:
a.mean()

10.5

In [102]:
a.sum()

42

In [103]:
a.std()

13.647344063956181

In [107]:
x = np.random.random((2, 2))

In [108]:
x

array([[0.47418256, 0.75884993],
       [0.52174109, 0.96794408]])

In [109]:
np.corrcoef(x)

array([[1., 1.],
       [1., 1.]])

## Broadcasting

In [110]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [113]:
b = np.array([4,5,7])
b.shape

(3,)

In [114]:
a + b

array([ 5,  7, 10])

In [126]:
## 2d arrays

a = np.array([[1,2,3], [4,5,6]])
b = np.array([3])

In [127]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [128]:
a * b

array([[ 3,  6,  9],
       [12, 15, 18]])

## Indexing

In [129]:
x = [1, 2, 3]

In [132]:
x[2]

3

In [135]:
a = ['a', 'b', 'c', 'd']
[0, 1, 2, 3]
## The index that you define, the element is inclusive
a[1:]

['b', 'c', 'd']

In [145]:
## The last index ignores the last element
a[0:]

['a', 'b', 'c', 'd']

In [146]:
## Give me all elements until just before the last one
a[:-1]

['a', 'b', 'c']

In [147]:
a[-5:-2]

['a', 'b']

In [149]:
a[:-4]

[]

In [150]:
a = np.array([[1,2,3], [4,5,6], [6,7,8]])
a.shape

(3, 3)

In [153]:
a[1][1]

5

In [154]:
a[1,1]

5

In [155]:
a[:2, :1]

array([[1],
       [4]])

In [158]:
a[:8, :8]

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [159]:
a[::-1]

array([[6, 7, 8],
       [4, 5, 6],
       [1, 2, 3]])

In [161]:
a[:4, :1]

array([[1],
       [4],
       [6]])

## Concatenation

In [185]:
a = np.array([[1, 2, 3]])
b = np.array([[4,5,6]])

In [178]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

## Stacking

In [165]:
## Vertical Stacking
c = np.vstack((a,b))

In [166]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
c.shape

(2, 3)

In [186]:
## Horizontal Stacking
d = np.hstack((a, b))

In [187]:
d

array([[1, 2, 3, 4, 5, 6]])

In [179]:
## Column wise stacking
e = np.column_stack((a,b))

In [227]:
e

array([[1, 4],
       [2, 5],
       [3, 6]])

In [182]:
b

array([4, 5, 6])

In [180]:
e

array([[1, 4],
       [2, 5],
       [3, 6]])

In [183]:
e.shape

(3, 2)

## Splitting Arrays

In [188]:
x = np.arange(16)

In [189]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [190]:
y = x.reshape(4, 4)

In [191]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [192]:
## Vsplits and Hsplits

In [211]:
z = np.hsplit(y, 2)

In [202]:
z = np.hsplit(y, 4)

In [212]:
z

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [232]:
k = np.vsplit(y, 4)

In [233]:
k

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [234]:
## Faster
## Consumes Less Memory

In [235]:
import sys

In [236]:
py_array = range(1000)

In [237]:
print("Size of each element in python list of py_array in bytes:", 
      sys.getsizeof(py_array))

Size of each element in python list of py_array in bytes: 48


In [238]:
print("Size of entire python list  in bytes:", 
      sys.getsizeof(py_array) * len(py_array))

Size of entire python list  in bytes: 48000


In [239]:
np_array = np.arange(1000)

In [240]:
print("Size of each element in numpy array of np_array in bytes:", 
      np_array.itemsize)

Size of each element in numpy array of np_array in bytes: 8
